package com.whatbi.zq.dal.domain;

import com.common.mybatis.util.Page;
import java.util.ArrayList;
import java.util.List;

public class ZqFirstDebtExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    protected Page page;

    protected String fullOrgPath;

    protected String owner;

    public ZqFirstDebtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setPage(Page page) {
        this.page=page;
    }

    public Page getPage() {
        return page;
    }

    public void setFullOrgPath(String fullOrgPath) {
        this.fullOrgPath=fullOrgPath;
    }

    public String getFullOrgPath() {
        return fullOrgPath;
    }

    public void setOwner(String owner) {
        this.owner=owner;
    }

    public String getOwner() {
        return owner;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zq_first_debt
     *
     * @mbggenerated Wed Dec 10 22:09:09 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("is_deleted like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("is_deleted not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Long value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Long value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Long value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Long value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Long value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Long> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Long> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Long value1, Long value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Long value1, Long value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("modifier like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("modifier not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("modifier not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Long value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Long value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Long value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Long value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Long value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Long> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Long> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Long value1, Long value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Long value1, Long value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andCIdIsNull() {
            addCriterion("c_id is null");
            return (Criteria) this;
        }

        public Criteria andCIdIsNotNull() {
            addCriterion("c_id is not null");
            return (Criteria) this;
        }

        public Criteria andCIdEqualTo(Long value) {
            addCriterion("c_id =", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotEqualTo(Long value) {
            addCriterion("c_id <>", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThan(Long value) {
            addCriterion("c_id >", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThanOrEqualTo(Long value) {
            addCriterion("c_id >=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThan(Long value) {
            addCriterion("c_id <", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThanOrEqualTo(Long value) {
            addCriterion("c_id <=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdIn(List<Long> values) {
            addCriterion("c_id in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotIn(List<Long> values) {
            addCriterion("c_id not in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdBetween(Long value1, Long value2) {
            addCriterion("c_id between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotBetween(Long value1, Long value2) {
            addCriterion("c_id not between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andDMoneyIsNull() {
            addCriterion("d_money is null");
            return (Criteria) this;
        }

        public Criteria andDMoneyIsNotNull() {
            addCriterion("d_money is not null");
            return (Criteria) this;
        }

        public Criteria andDMoneyEqualTo(Double value) {
            addCriterion("d_money =", value, "dMoney");
            return (Criteria) this;
        }

        public Criteria andDMoneyNotEqualTo(Double value) {
            addCriterion("d_money <>", value, "dMoney");
            return (Criteria) this;
        }

        public Criteria andDMoneyGreaterThan(Double value) {
            addCriterion("d_money >", value, "dMoney");
            return (Criteria) this;
        }

        public Criteria andDMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("d_money >=", value, "dMoney");
            return (Criteria) this;
        }

        public Criteria andDMoneyLessThan(Double value) {
            addCriterion("d_money <", value, "dMoney");
            return (Criteria) this;
        }

        public Criteria andDMoneyLessThanOrEqualTo(Double value) {
            addCriterion("d_money <=", value, "dMoney");
            return (Criteria) this;
        }

        public Criteria andDMoneyIn(List<Double> values) {
            addCriterion("d_money in", values, "dMoney");
            return (Criteria) this;
        }

        public Criteria andDMoneyNotIn(List<Double> values) {
            addCriterion("d_money not in", values, "dMoney");
            return (Criteria) this;
        }

        public Criteria andDMoneyBetween(Double value1, Double value2) {
            addCriterion("d_money between", value1, value2, "dMoney");
            return (Criteria) this;
        }

        public Criteria andDMoneyNotBetween(Double value1, Double value2) {
            addCriterion("d_money not between", value1, value2, "dMoney");
            return (Criteria) this;
        }

        public Criteria andDUseMoneyIsNull() {
            addCriterion("d_use_money is null");
            return (Criteria) this;
        }

        public Criteria andDUseMoneyIsNotNull() {
            addCriterion("d_use_money is not null");
            return (Criteria) this;
        }

        public Criteria andDUseMoneyEqualTo(Double value) {
            addCriterion("d_use_money =", value, "dUseMoney");
            return (Criteria) this;
        }

        public Criteria andDUseMoneyNotEqualTo(Double value) {
            addCriterion("d_use_money <>", value, "dUseMoney");
            return (Criteria) this;
        }

        public Criteria andDUseMoneyGreaterThan(Double value) {
            addCriterion("d_use_money >", value, "dUseMoney");
            return (Criteria) this;
        }

        public Criteria andDUseMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("d_use_money >=", value, "dUseMoney");
            return (Criteria) this;
        }

        public Criteria andDUseMoneyLessThan(Double value) {
            addCriterion("d_use_money <", value, "dUseMoney");
            return (Criteria) this;
        }

        public Criteria andDUseMoneyLessThanOrEqualTo(Double value) {
            addCriterion("d_use_money <=", value, "dUseMoney");
            return (Criteria) this;
        }

        public Criteria andDUseMoneyIn(List<Double> values) {
            addCriterion("d_use_money in", values, "dUseMoney");
            return (Criteria) this;
        }

        public Criteria andDUseMoneyNotIn(List<Double> values) {
            addCriterion("d_use_money not in", values, "dUseMoney");
            return (Criteria) this;
        }

        public Criteria andDUseMoneyBetween(Double value1, Double value2) {
            addCriterion("d_use_money between", value1, value2, "dUseMoney");
            return (Criteria) this;
        }

        public Criteria andDUseMoneyNotBetween(Double value1, Double value2) {
            addCriterion("d_use_money not between", value1, value2, "dUseMoney");
            return (Criteria) this;
        }

        public Criteria andDStartdateIsNull() {
            addCriterion("d_startdate is null");
            return (Criteria) this;
        }

        public Criteria andDStartdateIsNotNull() {
            addCriterion("d_startdate is not null");
            return (Criteria) this;
        }

        public Criteria andDStartdateEqualTo(Long value) {
            addCriterion("d_startdate =", value, "dStartdate");
            return (Criteria) this;
        }

        public Criteria andDStartdateNotEqualTo(Long value) {
            addCriterion("d_startdate <>", value, "dStartdate");
            return (Criteria) this;
        }

        public Criteria andDStartdateGreaterThan(Long value) {
            addCriterion("d_startdate >", value, "dStartdate");
            return (Criteria) this;
        }

        public Criteria andDStartdateGreaterThanOrEqualTo(Long value) {
            addCriterion("d_startdate >=", value, "dStartdate");
            return (Criteria) this;
        }

        public Criteria andDStartdateLessThan(Long value) {
            addCriterion("d_startdate <", value, "dStartdate");
            return (Criteria) this;
        }

        public Criteria andDStartdateLessThanOrEqualTo(Long value) {
            addCriterion("d_startdate <=", value, "dStartdate");
            return (Criteria) this;
        }

        public Criteria andDStartdateIn(List<Long> values) {
            addCriterion("d_startdate in", values, "dStartdate");
            return (Criteria) this;
        }

        public Criteria andDStartdateNotIn(List<Long> values) {
            addCriterion("d_startdate not in", values, "dStartdate");
            return (Criteria) this;
        }

        public Criteria andDStartdateBetween(Long value1, Long value2) {
            addCriterion("d_startdate between", value1, value2, "dStartdate");
            return (Criteria) this;
        }

        public Criteria andDStartdateNotBetween(Long value1, Long value2) {
            addCriterion("d_startdate not between", value1, value2, "dStartdate");
            return (Criteria) this;
        }

        public Criteria andDEnddateIsNull() {
            addCriterion("d_enddate is null");
            return (Criteria) this;
        }

        public Criteria andDEnddateIsNotNull() {
            addCriterion("d_enddate is not null");
            return (Criteria) this;
        }

        public Criteria andDEnddateEqualTo(Long value) {
            addCriterion("d_enddate =", value, "dEnddate");
            return (Criteria) this;
        }

        public Criteria andDEnddateNotEqualTo(Long value) {
            addCriterion("d_enddate <>", value, "dEnddate");
            return (Criteria) this;
        }

        public Criteria andDEnddateGreaterThan(Long value) {
            addCriterion("d_enddate >", value, "dEnddate");
            return (Criteria) this;
        }

        public Criteria andDEnddateGreaterThanOrEqualTo(Long value) {
            addCriterion("d_enddate >=", value, "dEnddate");
            return (Criteria) this;
        }

        public Criteria andDEnddateLessThan(Long value) {
            addCriterion("d_enddate <", value, "dEnddate");
            return (Criteria) this;
        }

        public Criteria andDEnddateLessThanOrEqualTo(Long value) {
            addCriterion("d_enddate <=", value, "dEnddate");
            return (Criteria) this;
        }

        public Criteria andDEnddateIn(List<Long> values) {
            addCriterion("d_enddate in", values, "dEnddate");
            return (Criteria) this;
        }

        public Criteria andDEnddateNotIn(List<Long> values) {
            addCriterion("d_enddate not in", values, "dEnddate");
            return (Criteria) this;
        }

        public Criteria andDEnddateBetween(Long value1, Long value2) {
            addCriterion("d_enddate between", value1, value2, "dEnddate");
            return (Criteria) this;
        }

        public Criteria andDEnddateNotBetween(Long value1, Long value2) {
            addCriterion("d_enddate not between", value1, value2, "dEnddate");
            return (Criteria) this;
        }

        public Criteria andDRateIsNull() {
            addCriterion("d_rate is null");
            return (Criteria) this;
        }

        public Criteria andDRateIsNotNull() {
            addCriterion("d_rate is not null");
            return (Criteria) this;
        }

        public Criteria andDRateEqualTo(Double value) {
            addCriterion("d_rate =", value, "dRate");
            return (Criteria) this;
        }

        public Criteria andDRateNotEqualTo(Double value) {
            addCriterion("d_rate <>", value, "dRate");
            return (Criteria) this;
        }

        public Criteria andDRateGreaterThan(Double value) {
            addCriterion("d_rate >", value, "dRate");
            return (Criteria) this;
        }

        public Criteria andDRateGreaterThanOrEqualTo(Double value) {
            addCriterion("d_rate >=", value, "dRate");
            return (Criteria) this;
        }

        public Criteria andDRateLessThan(Double value) {
            addCriterion("d_rate <", value, "dRate");
            return (Criteria) this;
        }

        public Criteria andDRateLessThanOrEqualTo(Double value) {
            addCriterion("d_rate <=", value, "dRate");
            return (Criteria) this;
        }

        public Criteria andDRateIn(List<Double> values) {
            addCriterion("d_rate in", values, "dRate");
            return (Criteria) this;
        }

        public Criteria andDRateNotIn(List<Double> values) {
            addCriterion("d_rate not in", values, "dRate");
            return (Criteria) this;
        }

        public Criteria andDRateBetween(Double value1, Double value2) {
            addCriterion("d_rate between", value1, value2, "dRate");
            return (Criteria) this;
        }

        public Criteria andDRateNotBetween(Double value1, Double value2) {
            addCriterion("d_rate not between", value1, value2, "dRate");
            return (Criteria) this;
        }

        public Criteria andDTypeIsNull() {
            addCriterion("d_type is null");
            return (Criteria) this;
        }

        public Criteria andDTypeIsNotNull() {
            addCriterion("d_type is not null");
            return (Criteria) this;
        }

        public Criteria andDTypeEqualTo(Integer value) {
            addCriterion("d_type =", value, "dType");
            return (Criteria) this;
        }

        public Criteria andDTypeNotEqualTo(Integer value) {
            addCriterion("d_type <>", value, "dType");
            return (Criteria) this;
        }

        public Criteria andDTypeGreaterThan(Integer value) {
            addCriterion("d_type >", value, "dType");
            return (Criteria) this;
        }

        public Criteria andDTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("d_type >=", value, "dType");
            return (Criteria) this;
        }

        public Criteria andDTypeLessThan(Integer value) {
            addCriterion("d_type <", value, "dType");
            return (Criteria) this;
        }

        public Criteria andDTypeLessThanOrEqualTo(Integer value) {
            addCriterion("d_type <=", value, "dType");
            return (Criteria) this;
        }

        public Criteria andDTypeIn(List<Integer> values) {
            addCriterion("d_type in", values, "dType");
            return (Criteria) this;
        }

        public Criteria andDTypeNotIn(List<Integer> values) {
            addCriterion("d_type not in", values, "dType");
            return (Criteria) this;
        }

        public Criteria andDTypeBetween(Integer value1, Integer value2) {
            addCriterion("d_type between", value1, value2, "dType");
            return (Criteria) this;
        }

        public Criteria andDTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("d_type not between", value1, value2, "dType");
            return (Criteria) this;
        }

        public Criteria andDMortgageIsNull() {
            addCriterion("d_mortgage is null");
            return (Criteria) this;
        }

        public Criteria andDMortgageIsNotNull() {
            addCriterion("d_mortgage is not null");
            return (Criteria) this;
        }

        public Criteria andDMortgageEqualTo(Integer value) {
            addCriterion("d_mortgage =", value, "dMortgage");
            return (Criteria) this;
        }

        public Criteria andDMortgageNotEqualTo(Integer value) {
            addCriterion("d_mortgage <>", value, "dMortgage");
            return (Criteria) this;
        }

        public Criteria andDMortgageGreaterThan(Integer value) {
            addCriterion("d_mortgage >", value, "dMortgage");
            return (Criteria) this;
        }

        public Criteria andDMortgageGreaterThanOrEqualTo(Integer value) {
            addCriterion("d_mortgage >=", value, "dMortgage");
            return (Criteria) this;
        }

        public Criteria andDMortgageLessThan(Integer value) {
            addCriterion("d_mortgage <", value, "dMortgage");
            return (Criteria) this;
        }

        public Criteria andDMortgageLessThanOrEqualTo(Integer value) {
            addCriterion("d_mortgage <=", value, "dMortgage");
            return (Criteria) this;
        }

        public Criteria andDMortgageIn(List<Integer> values) {
            addCriterion("d_mortgage in", values, "dMortgage");
            return (Criteria) this;
        }

        public Criteria andDMortgageNotIn(List<Integer> values) {
            addCriterion("d_mortgage not in", values, "dMortgage");
            return (Criteria) this;
        }

        public Criteria andDMortgageBetween(Integer value1, Integer value2) {
            addCriterion("d_mortgage between", value1, value2, "dMortgage");
            return (Criteria) this;
        }

        public Criteria andDMortgageNotBetween(Integer value1, Integer value2) {
            addCriterion("d_mortgage not between", value1, value2, "dMortgage");
            return (Criteria) this;
        }

        public Criteria andDUseIsNull() {
            addCriterion("d_use is null");
            return (Criteria) this;
        }

        public Criteria andDUseIsNotNull() {
            addCriterion("d_use is not null");
            return (Criteria) this;
        }

        public Criteria andDUseEqualTo(String value) {
            addCriterion("d_use =", value, "dUse");
            return (Criteria) this;
        }

        public Criteria andDUseNotEqualTo(String value) {
            addCriterion("d_use <>", value, "dUse");
            return (Criteria) this;
        }

        public Criteria andDUseGreaterThan(String value) {
            addCriterion("d_use >", value, "dUse");
            return (Criteria) this;
        }

        public Criteria andDUseGreaterThanOrEqualTo(String value) {
            addCriterion("d_use >=", value, "dUse");
            return (Criteria) this;
        }

        public Criteria andDUseLessThan(String value) {
            addCriterion("d_use <", value, "dUse");
            return (Criteria) this;
        }

        public Criteria andDUseLessThanOrEqualTo(String value) {
            addCriterion("d_use <=", value, "dUse");
            return (Criteria) this;
        }

        public Criteria andDUseLike(String value) {
            addCriterion("d_use like", value, "dUse");
            return (Criteria) this;
        }

        public Criteria andDUseNotLike(String value) {
            addCriterion("d_use not like", value, "dUse");
            return (Criteria) this;
        }

        public Criteria andDUseIn(List<String> values) {
            addCriterion("d_use in", values, "dUse");
            return (Criteria) this;
        }

        public Criteria andDUseNotIn(List<String> values) {
            addCriterion("d_use not in", values, "dUse");
            return (Criteria) this;
        }

        public Criteria andDUseBetween(String value1, String value2) {
            addCriterion("d_use between", value1, value2, "dUse");
            return (Criteria) this;
        }

        public Criteria andDUseNotBetween(String value1, String value2) {
            addCriterion("d_use not between", value1, value2, "dUse");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(Integer value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(Integer value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(Integer value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(Integer value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(Integer value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(Integer value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<Integer> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<Integer> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(Integer value1, Integer value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(Integer value1, Integer value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zq_first_debt
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 10 22:09:09 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zq_first_debt
     *
     * @mbggenerated Wed Dec 10 22:09:09 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}