package com.whatbi.zq.dal.domain;

import com.common.mybatis.util.Page;
import java.util.ArrayList;
import java.util.List;

public class ZqReportDebtTransferExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    protected Page page;

    protected String fullOrgPath;

    protected String owner;

    public ZqReportDebtTransferExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setPage(Page page) {
        this.page=page;
    }

    public Page getPage() {
        return page;
    }

    public void setFullOrgPath(String fullOrgPath) {
        this.fullOrgPath=fullOrgPath;
    }

    public String getFullOrgPath() {
        return fullOrgPath;
    }

    public void setOwner(String owner) {
        this.owner=owner;
    }

    public String getOwner() {
        return owner;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zq_report_debt_transfer
     *
     * @mbggenerated Sun Dec 07 23:32:29 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("is_deleted like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("is_deleted not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Long value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Long value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Long value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Long value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Long value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Long> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Long> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Long value1, Long value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Long value1, Long value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("modifier like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("modifier not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("modifier not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Long value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Long value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Long value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Long value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Long value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Long> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Long> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Long value1, Long value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Long value1, Long value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andRNumIsNull() {
            addCriterion("r_num is null");
            return (Criteria) this;
        }

        public Criteria andRNumIsNotNull() {
            addCriterion("r_num is not null");
            return (Criteria) this;
        }

        public Criteria andRNumEqualTo(String value) {
            addCriterion("r_num =", value, "rNum");
            return (Criteria) this;
        }

        public Criteria andRNumNotEqualTo(String value) {
            addCriterion("r_num <>", value, "rNum");
            return (Criteria) this;
        }

        public Criteria andRNumGreaterThan(String value) {
            addCriterion("r_num >", value, "rNum");
            return (Criteria) this;
        }

        public Criteria andRNumGreaterThanOrEqualTo(String value) {
            addCriterion("r_num >=", value, "rNum");
            return (Criteria) this;
        }

        public Criteria andRNumLessThan(String value) {
            addCriterion("r_num <", value, "rNum");
            return (Criteria) this;
        }

        public Criteria andRNumLessThanOrEqualTo(String value) {
            addCriterion("r_num <=", value, "rNum");
            return (Criteria) this;
        }

        public Criteria andRNumLike(String value) {
            addCriterion("r_num like", value, "rNum");
            return (Criteria) this;
        }

        public Criteria andRNumNotLike(String value) {
            addCriterion("r_num not like", value, "rNum");
            return (Criteria) this;
        }

        public Criteria andRNumIn(List<String> values) {
            addCriterion("r_num in", values, "rNum");
            return (Criteria) this;
        }

        public Criteria andRNumNotIn(List<String> values) {
            addCriterion("r_num not in", values, "rNum");
            return (Criteria) this;
        }

        public Criteria andRNumBetween(String value1, String value2) {
            addCriterion("r_num between", value1, value2, "rNum");
            return (Criteria) this;
        }

        public Criteria andRNumNotBetween(String value1, String value2) {
            addCriterion("r_num not between", value1, value2, "rNum");
            return (Criteria) this;
        }

        public Criteria andRTypeIsNull() {
            addCriterion("r_type is null");
            return (Criteria) this;
        }

        public Criteria andRTypeIsNotNull() {
            addCriterion("r_type is not null");
            return (Criteria) this;
        }

        public Criteria andRTypeEqualTo(String value) {
            addCriterion("r_type =", value, "rType");
            return (Criteria) this;
        }

        public Criteria andRTypeNotEqualTo(String value) {
            addCriterion("r_type <>", value, "rType");
            return (Criteria) this;
        }

        public Criteria andRTypeGreaterThan(String value) {
            addCriterion("r_type >", value, "rType");
            return (Criteria) this;
        }

        public Criteria andRTypeGreaterThanOrEqualTo(String value) {
            addCriterion("r_type >=", value, "rType");
            return (Criteria) this;
        }

        public Criteria andRTypeLessThan(String value) {
            addCriterion("r_type <", value, "rType");
            return (Criteria) this;
        }

        public Criteria andRTypeLessThanOrEqualTo(String value) {
            addCriterion("r_type <=", value, "rType");
            return (Criteria) this;
        }

        public Criteria andRTypeLike(String value) {
            addCriterion("r_type like", value, "rType");
            return (Criteria) this;
        }

        public Criteria andRTypeNotLike(String value) {
            addCriterion("r_type not like", value, "rType");
            return (Criteria) this;
        }

        public Criteria andRTypeIn(List<String> values) {
            addCriterion("r_type in", values, "rType");
            return (Criteria) this;
        }

        public Criteria andRTypeNotIn(List<String> values) {
            addCriterion("r_type not in", values, "rType");
            return (Criteria) this;
        }

        public Criteria andRTypeBetween(String value1, String value2) {
            addCriterion("r_type between", value1, value2, "rType");
            return (Criteria) this;
        }

        public Criteria andRTypeNotBetween(String value1, String value2) {
            addCriterion("r_type not between", value1, value2, "rType");
            return (Criteria) this;
        }

        public Criteria andRInitDateIsNull() {
            addCriterion("r_init_date is null");
            return (Criteria) this;
        }

        public Criteria andRInitDateIsNotNull() {
            addCriterion("r_init_date is not null");
            return (Criteria) this;
        }

        public Criteria andRInitDateEqualTo(String value) {
            addCriterion("r_init_date =", value, "rInitDate");
            return (Criteria) this;
        }

        public Criteria andRInitDateNotEqualTo(String value) {
            addCriterion("r_init_date <>", value, "rInitDate");
            return (Criteria) this;
        }

        public Criteria andRInitDateGreaterThan(String value) {
            addCriterion("r_init_date >", value, "rInitDate");
            return (Criteria) this;
        }

        public Criteria andRInitDateGreaterThanOrEqualTo(String value) {
            addCriterion("r_init_date >=", value, "rInitDate");
            return (Criteria) this;
        }

        public Criteria andRInitDateLessThan(String value) {
            addCriterion("r_init_date <", value, "rInitDate");
            return (Criteria) this;
        }

        public Criteria andRInitDateLessThanOrEqualTo(String value) {
            addCriterion("r_init_date <=", value, "rInitDate");
            return (Criteria) this;
        }

        public Criteria andRInitDateLike(String value) {
            addCriterion("r_init_date like", value, "rInitDate");
            return (Criteria) this;
        }

        public Criteria andRInitDateNotLike(String value) {
            addCriterion("r_init_date not like", value, "rInitDate");
            return (Criteria) this;
        }

        public Criteria andRInitDateIn(List<String> values) {
            addCriterion("r_init_date in", values, "rInitDate");
            return (Criteria) this;
        }

        public Criteria andRInitDateNotIn(List<String> values) {
            addCriterion("r_init_date not in", values, "rInitDate");
            return (Criteria) this;
        }

        public Criteria andRInitDateBetween(String value1, String value2) {
            addCriterion("r_init_date between", value1, value2, "rInitDate");
            return (Criteria) this;
        }

        public Criteria andRInitDateNotBetween(String value1, String value2) {
            addCriterion("r_init_date not between", value1, value2, "rInitDate");
            return (Criteria) this;
        }

        public Criteria andRMoneyIsNull() {
            addCriterion("r_money is null");
            return (Criteria) this;
        }

        public Criteria andRMoneyIsNotNull() {
            addCriterion("r_money is not null");
            return (Criteria) this;
        }

        public Criteria andRMoneyEqualTo(String value) {
            addCriterion("r_money =", value, "rMoney");
            return (Criteria) this;
        }

        public Criteria andRMoneyNotEqualTo(String value) {
            addCriterion("r_money <>", value, "rMoney");
            return (Criteria) this;
        }

        public Criteria andRMoneyGreaterThan(String value) {
            addCriterion("r_money >", value, "rMoney");
            return (Criteria) this;
        }

        public Criteria andRMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("r_money >=", value, "rMoney");
            return (Criteria) this;
        }

        public Criteria andRMoneyLessThan(String value) {
            addCriterion("r_money <", value, "rMoney");
            return (Criteria) this;
        }

        public Criteria andRMoneyLessThanOrEqualTo(String value) {
            addCriterion("r_money <=", value, "rMoney");
            return (Criteria) this;
        }

        public Criteria andRMoneyLike(String value) {
            addCriterion("r_money like", value, "rMoney");
            return (Criteria) this;
        }

        public Criteria andRMoneyNotLike(String value) {
            addCriterion("r_money not like", value, "rMoney");
            return (Criteria) this;
        }

        public Criteria andRMoneyIn(List<String> values) {
            addCriterion("r_money in", values, "rMoney");
            return (Criteria) this;
        }

        public Criteria andRMoneyNotIn(List<String> values) {
            addCriterion("r_money not in", values, "rMoney");
            return (Criteria) this;
        }

        public Criteria andRMoneyBetween(String value1, String value2) {
            addCriterion("r_money between", value1, value2, "rMoney");
            return (Criteria) this;
        }

        public Criteria andRMoneyNotBetween(String value1, String value2) {
            addCriterion("r_money not between", value1, value2, "rMoney");
            return (Criteria) this;
        }

        public Criteria andRNextDateIsNull() {
            addCriterion("r_next_date is null");
            return (Criteria) this;
        }

        public Criteria andRNextDateIsNotNull() {
            addCriterion("r_next_date is not null");
            return (Criteria) this;
        }

        public Criteria andRNextDateEqualTo(String value) {
            addCriterion("r_next_date =", value, "rNextDate");
            return (Criteria) this;
        }

        public Criteria andRNextDateNotEqualTo(String value) {
            addCriterion("r_next_date <>", value, "rNextDate");
            return (Criteria) this;
        }

        public Criteria andRNextDateGreaterThan(String value) {
            addCriterion("r_next_date >", value, "rNextDate");
            return (Criteria) this;
        }

        public Criteria andRNextDateGreaterThanOrEqualTo(String value) {
            addCriterion("r_next_date >=", value, "rNextDate");
            return (Criteria) this;
        }

        public Criteria andRNextDateLessThan(String value) {
            addCriterion("r_next_date <", value, "rNextDate");
            return (Criteria) this;
        }

        public Criteria andRNextDateLessThanOrEqualTo(String value) {
            addCriterion("r_next_date <=", value, "rNextDate");
            return (Criteria) this;
        }

        public Criteria andRNextDateLike(String value) {
            addCriterion("r_next_date like", value, "rNextDate");
            return (Criteria) this;
        }

        public Criteria andRNextDateNotLike(String value) {
            addCriterion("r_next_date not like", value, "rNextDate");
            return (Criteria) this;
        }

        public Criteria andRNextDateIn(List<String> values) {
            addCriterion("r_next_date in", values, "rNextDate");
            return (Criteria) this;
        }

        public Criteria andRNextDateNotIn(List<String> values) {
            addCriterion("r_next_date not in", values, "rNextDate");
            return (Criteria) this;
        }

        public Criteria andRNextDateBetween(String value1, String value2) {
            addCriterion("r_next_date between", value1, value2, "rNextDate");
            return (Criteria) this;
        }

        public Criteria andRNextDateNotBetween(String value1, String value2) {
            addCriterion("r_next_date not between", value1, value2, "rNextDate");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyIsNull() {
            addCriterion("r_next_money is null");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyIsNotNull() {
            addCriterion("r_next_money is not null");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyEqualTo(String value) {
            addCriterion("r_next_money =", value, "rNextMoney");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyNotEqualTo(String value) {
            addCriterion("r_next_money <>", value, "rNextMoney");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyGreaterThan(String value) {
            addCriterion("r_next_money >", value, "rNextMoney");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("r_next_money >=", value, "rNextMoney");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyLessThan(String value) {
            addCriterion("r_next_money <", value, "rNextMoney");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyLessThanOrEqualTo(String value) {
            addCriterion("r_next_money <=", value, "rNextMoney");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyLike(String value) {
            addCriterion("r_next_money like", value, "rNextMoney");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyNotLike(String value) {
            addCriterion("r_next_money not like", value, "rNextMoney");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyIn(List<String> values) {
            addCriterion("r_next_money in", values, "rNextMoney");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyNotIn(List<String> values) {
            addCriterion("r_next_money not in", values, "rNextMoney");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyBetween(String value1, String value2) {
            addCriterion("r_next_money between", value1, value2, "rNextMoney");
            return (Criteria) this;
        }

        public Criteria andRNextMoneyNotBetween(String value1, String value2) {
            addCriterion("r_next_money not between", value1, value2, "rNextMoney");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyIsNull() {
            addCriterion("r_all_money is null");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyIsNotNull() {
            addCriterion("r_all_money is not null");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyEqualTo(String value) {
            addCriterion("r_all_money =", value, "rAllMoney");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyNotEqualTo(String value) {
            addCriterion("r_all_money <>", value, "rAllMoney");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyGreaterThan(String value) {
            addCriterion("r_all_money >", value, "rAllMoney");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("r_all_money >=", value, "rAllMoney");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyLessThan(String value) {
            addCriterion("r_all_money <", value, "rAllMoney");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyLessThanOrEqualTo(String value) {
            addCriterion("r_all_money <=", value, "rAllMoney");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyLike(String value) {
            addCriterion("r_all_money like", value, "rAllMoney");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyNotLike(String value) {
            addCriterion("r_all_money not like", value, "rAllMoney");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyIn(List<String> values) {
            addCriterion("r_all_money in", values, "rAllMoney");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyNotIn(List<String> values) {
            addCriterion("r_all_money not in", values, "rAllMoney");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyBetween(String value1, String value2) {
            addCriterion("r_all_money between", value1, value2, "rAllMoney");
            return (Criteria) this;
        }

        public Criteria andRAllMoneyNotBetween(String value1, String value2) {
            addCriterion("r_all_money not between", value1, value2, "rAllMoney");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zq_report_debt_transfer
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 07 23:32:29 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zq_report_debt_transfer
     *
     * @mbggenerated Sun Dec 07 23:32:29 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}