package com.whatbi.zq.dal.domain;

import com.common.mybatis.util.Page;
import java.util.ArrayList;
import java.util.List;

public class ZqReportDebtListExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    protected Page page;

    protected String fullOrgPath;

    protected String owner;

    public ZqReportDebtListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setPage(Page page) {
        this.page=page;
    }

    public Page getPage() {
        return page;
    }

    public void setFullOrgPath(String fullOrgPath) {
        this.fullOrgPath=fullOrgPath;
    }

    public String getFullOrgPath() {
        return fullOrgPath;
    }

    public void setOwner(String owner) {
        this.owner=owner;
    }

    public String getOwner() {
        return owner;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zq_report_debt_list
     *
     * @mbggenerated Sun Dec 07 23:32:29 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("is_deleted like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("is_deleted not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Long value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Long value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Long value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Long value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Long value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Long> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Long> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Long value1, Long value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Long value1, Long value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("modifier like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("modifier not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("modifier not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Long value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Long value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Long value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Long value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Long value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Long> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Long> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Long value1, Long value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Long value1, Long value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andRepTraIdIsNull() {
            addCriterion("rep_tra_id is null");
            return (Criteria) this;
        }

        public Criteria andRepTraIdIsNotNull() {
            addCriterion("rep_tra_id is not null");
            return (Criteria) this;
        }

        public Criteria andRepTraIdEqualTo(String value) {
            addCriterion("rep_tra_id =", value, "repTraId");
            return (Criteria) this;
        }

        public Criteria andRepTraIdNotEqualTo(String value) {
            addCriterion("rep_tra_id <>", value, "repTraId");
            return (Criteria) this;
        }

        public Criteria andRepTraIdGreaterThan(String value) {
            addCriterion("rep_tra_id >", value, "repTraId");
            return (Criteria) this;
        }

        public Criteria andRepTraIdGreaterThanOrEqualTo(String value) {
            addCriterion("rep_tra_id >=", value, "repTraId");
            return (Criteria) this;
        }

        public Criteria andRepTraIdLessThan(String value) {
            addCriterion("rep_tra_id <", value, "repTraId");
            return (Criteria) this;
        }

        public Criteria andRepTraIdLessThanOrEqualTo(String value) {
            addCriterion("rep_tra_id <=", value, "repTraId");
            return (Criteria) this;
        }

        public Criteria andRepTraIdLike(String value) {
            addCriterion("rep_tra_id like", value, "repTraId");
            return (Criteria) this;
        }

        public Criteria andRepTraIdNotLike(String value) {
            addCriterion("rep_tra_id not like", value, "repTraId");
            return (Criteria) this;
        }

        public Criteria andRepTraIdIn(List<String> values) {
            addCriterion("rep_tra_id in", values, "repTraId");
            return (Criteria) this;
        }

        public Criteria andRepTraIdNotIn(List<String> values) {
            addCriterion("rep_tra_id not in", values, "repTraId");
            return (Criteria) this;
        }

        public Criteria andRepTraIdBetween(String value1, String value2) {
            addCriterion("rep_tra_id between", value1, value2, "repTraId");
            return (Criteria) this;
        }

        public Criteria andRepTraIdNotBetween(String value1, String value2) {
            addCriterion("rep_tra_id not between", value1, value2, "repTraId");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNull() {
            addCriterion("cust_name is null");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("cust_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("cust_name =", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("cust_name <>", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("cust_name >", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("cust_name >=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("cust_name <", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("cust_name <=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("cust_name like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("cust_name not like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameIn(List<String> values) {
            addCriterion("cust_name in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotIn(List<String> values) {
            addCriterion("cust_name not in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("cust_name between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("cust_name not between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustCardidIsNull() {
            addCriterion("cust_cardid is null");
            return (Criteria) this;
        }

        public Criteria andCustCardidIsNotNull() {
            addCriterion("cust_cardid is not null");
            return (Criteria) this;
        }

        public Criteria andCustCardidEqualTo(String value) {
            addCriterion("cust_cardid =", value, "custCardid");
            return (Criteria) this;
        }

        public Criteria andCustCardidNotEqualTo(String value) {
            addCriterion("cust_cardid <>", value, "custCardid");
            return (Criteria) this;
        }

        public Criteria andCustCardidGreaterThan(String value) {
            addCriterion("cust_cardid >", value, "custCardid");
            return (Criteria) this;
        }

        public Criteria andCustCardidGreaterThanOrEqualTo(String value) {
            addCriterion("cust_cardid >=", value, "custCardid");
            return (Criteria) this;
        }

        public Criteria andCustCardidLessThan(String value) {
            addCriterion("cust_cardid <", value, "custCardid");
            return (Criteria) this;
        }

        public Criteria andCustCardidLessThanOrEqualTo(String value) {
            addCriterion("cust_cardid <=", value, "custCardid");
            return (Criteria) this;
        }

        public Criteria andCustCardidLike(String value) {
            addCriterion("cust_cardid like", value, "custCardid");
            return (Criteria) this;
        }

        public Criteria andCustCardidNotLike(String value) {
            addCriterion("cust_cardid not like", value, "custCardid");
            return (Criteria) this;
        }

        public Criteria andCustCardidIn(List<String> values) {
            addCriterion("cust_cardid in", values, "custCardid");
            return (Criteria) this;
        }

        public Criteria andCustCardidNotIn(List<String> values) {
            addCriterion("cust_cardid not in", values, "custCardid");
            return (Criteria) this;
        }

        public Criteria andCustCardidBetween(String value1, String value2) {
            addCriterion("cust_cardid between", value1, value2, "custCardid");
            return (Criteria) this;
        }

        public Criteria andCustCardidNotBetween(String value1, String value2) {
            addCriterion("cust_cardid not between", value1, value2, "custCardid");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyIsNull() {
            addCriterion("debt_money is null");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyIsNotNull() {
            addCriterion("debt_money is not null");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyEqualTo(String value) {
            addCriterion("debt_money =", value, "debtMoney");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyNotEqualTo(String value) {
            addCriterion("debt_money <>", value, "debtMoney");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyGreaterThan(String value) {
            addCriterion("debt_money >", value, "debtMoney");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("debt_money >=", value, "debtMoney");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyLessThan(String value) {
            addCriterion("debt_money <", value, "debtMoney");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyLessThanOrEqualTo(String value) {
            addCriterion("debt_money <=", value, "debtMoney");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyLike(String value) {
            addCriterion("debt_money like", value, "debtMoney");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyNotLike(String value) {
            addCriterion("debt_money not like", value, "debtMoney");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyIn(List<String> values) {
            addCriterion("debt_money in", values, "debtMoney");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyNotIn(List<String> values) {
            addCriterion("debt_money not in", values, "debtMoney");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyBetween(String value1, String value2) {
            addCriterion("debt_money between", value1, value2, "debtMoney");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyNotBetween(String value1, String value2) {
            addCriterion("debt_money not between", value1, value2, "debtMoney");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyIsNull() {
            addCriterion("debt_money_copy is null");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyIsNotNull() {
            addCriterion("debt_money_copy is not null");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyEqualTo(String value) {
            addCriterion("debt_money_copy =", value, "debtMoneyCopy");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyNotEqualTo(String value) {
            addCriterion("debt_money_copy <>", value, "debtMoneyCopy");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyGreaterThan(String value) {
            addCriterion("debt_money_copy >", value, "debtMoneyCopy");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyGreaterThanOrEqualTo(String value) {
            addCriterion("debt_money_copy >=", value, "debtMoneyCopy");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyLessThan(String value) {
            addCriterion("debt_money_copy <", value, "debtMoneyCopy");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyLessThanOrEqualTo(String value) {
            addCriterion("debt_money_copy <=", value, "debtMoneyCopy");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyLike(String value) {
            addCriterion("debt_money_copy like", value, "debtMoneyCopy");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyNotLike(String value) {
            addCriterion("debt_money_copy not like", value, "debtMoneyCopy");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyIn(List<String> values) {
            addCriterion("debt_money_copy in", values, "debtMoneyCopy");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyNotIn(List<String> values) {
            addCriterion("debt_money_copy not in", values, "debtMoneyCopy");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyBetween(String value1, String value2) {
            addCriterion("debt_money_copy between", value1, value2, "debtMoneyCopy");
            return (Criteria) this;
        }

        public Criteria andDebtMoneyCopyNotBetween(String value1, String value2) {
            addCriterion("debt_money_copy not between", value1, value2, "debtMoneyCopy");
            return (Criteria) this;
        }

        public Criteria andCustJobIsNull() {
            addCriterion("cust_job is null");
            return (Criteria) this;
        }

        public Criteria andCustJobIsNotNull() {
            addCriterion("cust_job is not null");
            return (Criteria) this;
        }

        public Criteria andCustJobEqualTo(String value) {
            addCriterion("cust_job =", value, "custJob");
            return (Criteria) this;
        }

        public Criteria andCustJobNotEqualTo(String value) {
            addCriterion("cust_job <>", value, "custJob");
            return (Criteria) this;
        }

        public Criteria andCustJobGreaterThan(String value) {
            addCriterion("cust_job >", value, "custJob");
            return (Criteria) this;
        }

        public Criteria andCustJobGreaterThanOrEqualTo(String value) {
            addCriterion("cust_job >=", value, "custJob");
            return (Criteria) this;
        }

        public Criteria andCustJobLessThan(String value) {
            addCriterion("cust_job <", value, "custJob");
            return (Criteria) this;
        }

        public Criteria andCustJobLessThanOrEqualTo(String value) {
            addCriterion("cust_job <=", value, "custJob");
            return (Criteria) this;
        }

        public Criteria andCustJobLike(String value) {
            addCriterion("cust_job like", value, "custJob");
            return (Criteria) this;
        }

        public Criteria andCustJobNotLike(String value) {
            addCriterion("cust_job not like", value, "custJob");
            return (Criteria) this;
        }

        public Criteria andCustJobIn(List<String> values) {
            addCriterion("cust_job in", values, "custJob");
            return (Criteria) this;
        }

        public Criteria andCustJobNotIn(List<String> values) {
            addCriterion("cust_job not in", values, "custJob");
            return (Criteria) this;
        }

        public Criteria andCustJobBetween(String value1, String value2) {
            addCriterion("cust_job between", value1, value2, "custJob");
            return (Criteria) this;
        }

        public Criteria andCustJobNotBetween(String value1, String value2) {
            addCriterion("cust_job not between", value1, value2, "custJob");
            return (Criteria) this;
        }

        public Criteria andDebtUseIsNull() {
            addCriterion("debt_use is null");
            return (Criteria) this;
        }

        public Criteria andDebtUseIsNotNull() {
            addCriterion("debt_use is not null");
            return (Criteria) this;
        }

        public Criteria andDebtUseEqualTo(String value) {
            addCriterion("debt_use =", value, "debtUse");
            return (Criteria) this;
        }

        public Criteria andDebtUseNotEqualTo(String value) {
            addCriterion("debt_use <>", value, "debtUse");
            return (Criteria) this;
        }

        public Criteria andDebtUseGreaterThan(String value) {
            addCriterion("debt_use >", value, "debtUse");
            return (Criteria) this;
        }

        public Criteria andDebtUseGreaterThanOrEqualTo(String value) {
            addCriterion("debt_use >=", value, "debtUse");
            return (Criteria) this;
        }

        public Criteria andDebtUseLessThan(String value) {
            addCriterion("debt_use <", value, "debtUse");
            return (Criteria) this;
        }

        public Criteria andDebtUseLessThanOrEqualTo(String value) {
            addCriterion("debt_use <=", value, "debtUse");
            return (Criteria) this;
        }

        public Criteria andDebtUseLike(String value) {
            addCriterion("debt_use like", value, "debtUse");
            return (Criteria) this;
        }

        public Criteria andDebtUseNotLike(String value) {
            addCriterion("debt_use not like", value, "debtUse");
            return (Criteria) this;
        }

        public Criteria andDebtUseIn(List<String> values) {
            addCriterion("debt_use in", values, "debtUse");
            return (Criteria) this;
        }

        public Criteria andDebtUseNotIn(List<String> values) {
            addCriterion("debt_use not in", values, "debtUse");
            return (Criteria) this;
        }

        public Criteria andDebtUseBetween(String value1, String value2) {
            addCriterion("debt_use between", value1, value2, "debtUse");
            return (Criteria) this;
        }

        public Criteria andDebtUseNotBetween(String value1, String value2) {
            addCriterion("debt_use not between", value1, value2, "debtUse");
            return (Criteria) this;
        }

        public Criteria andDebtDateIsNull() {
            addCriterion("debt_date is null");
            return (Criteria) this;
        }

        public Criteria andDebtDateIsNotNull() {
            addCriterion("debt_date is not null");
            return (Criteria) this;
        }

        public Criteria andDebtDateEqualTo(String value) {
            addCriterion("debt_date =", value, "debtDate");
            return (Criteria) this;
        }

        public Criteria andDebtDateNotEqualTo(String value) {
            addCriterion("debt_date <>", value, "debtDate");
            return (Criteria) this;
        }

        public Criteria andDebtDateGreaterThan(String value) {
            addCriterion("debt_date >", value, "debtDate");
            return (Criteria) this;
        }

        public Criteria andDebtDateGreaterThanOrEqualTo(String value) {
            addCriterion("debt_date >=", value, "debtDate");
            return (Criteria) this;
        }

        public Criteria andDebtDateLessThan(String value) {
            addCriterion("debt_date <", value, "debtDate");
            return (Criteria) this;
        }

        public Criteria andDebtDateLessThanOrEqualTo(String value) {
            addCriterion("debt_date <=", value, "debtDate");
            return (Criteria) this;
        }

        public Criteria andDebtDateLike(String value) {
            addCriterion("debt_date like", value, "debtDate");
            return (Criteria) this;
        }

        public Criteria andDebtDateNotLike(String value) {
            addCriterion("debt_date not like", value, "debtDate");
            return (Criteria) this;
        }

        public Criteria andDebtDateIn(List<String> values) {
            addCriterion("debt_date in", values, "debtDate");
            return (Criteria) this;
        }

        public Criteria andDebtDateNotIn(List<String> values) {
            addCriterion("debt_date not in", values, "debtDate");
            return (Criteria) this;
        }

        public Criteria andDebtDateBetween(String value1, String value2) {
            addCriterion("debt_date between", value1, value2, "debtDate");
            return (Criteria) this;
        }

        public Criteria andDebtDateNotBetween(String value1, String value2) {
            addCriterion("debt_date not between", value1, value2, "debtDate");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitIsNull() {
            addCriterion("debt_time_limit is null");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitIsNotNull() {
            addCriterion("debt_time_limit is not null");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitEqualTo(String value) {
            addCriterion("debt_time_limit =", value, "debtTimeLimit");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitNotEqualTo(String value) {
            addCriterion("debt_time_limit <>", value, "debtTimeLimit");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitGreaterThan(String value) {
            addCriterion("debt_time_limit >", value, "debtTimeLimit");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitGreaterThanOrEqualTo(String value) {
            addCriterion("debt_time_limit >=", value, "debtTimeLimit");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitLessThan(String value) {
            addCriterion("debt_time_limit <", value, "debtTimeLimit");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitLessThanOrEqualTo(String value) {
            addCriterion("debt_time_limit <=", value, "debtTimeLimit");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitLike(String value) {
            addCriterion("debt_time_limit like", value, "debtTimeLimit");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitNotLike(String value) {
            addCriterion("debt_time_limit not like", value, "debtTimeLimit");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitIn(List<String> values) {
            addCriterion("debt_time_limit in", values, "debtTimeLimit");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitNotIn(List<String> values) {
            addCriterion("debt_time_limit not in", values, "debtTimeLimit");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitBetween(String value1, String value2) {
            addCriterion("debt_time_limit between", value1, value2, "debtTimeLimit");
            return (Criteria) this;
        }

        public Criteria andDebtTimeLimitNotBetween(String value1, String value2) {
            addCriterion("debt_time_limit not between", value1, value2, "debtTimeLimit");
            return (Criteria) this;
        }

        public Criteria andMonthNumIsNull() {
            addCriterion("month_num is null");
            return (Criteria) this;
        }

        public Criteria andMonthNumIsNotNull() {
            addCriterion("month_num is not null");
            return (Criteria) this;
        }

        public Criteria andMonthNumEqualTo(String value) {
            addCriterion("month_num =", value, "monthNum");
            return (Criteria) this;
        }

        public Criteria andMonthNumNotEqualTo(String value) {
            addCriterion("month_num <>", value, "monthNum");
            return (Criteria) this;
        }

        public Criteria andMonthNumGreaterThan(String value) {
            addCriterion("month_num >", value, "monthNum");
            return (Criteria) this;
        }

        public Criteria andMonthNumGreaterThanOrEqualTo(String value) {
            addCriterion("month_num >=", value, "monthNum");
            return (Criteria) this;
        }

        public Criteria andMonthNumLessThan(String value) {
            addCriterion("month_num <", value, "monthNum");
            return (Criteria) this;
        }

        public Criteria andMonthNumLessThanOrEqualTo(String value) {
            addCriterion("month_num <=", value, "monthNum");
            return (Criteria) this;
        }

        public Criteria andMonthNumLike(String value) {
            addCriterion("month_num like", value, "monthNum");
            return (Criteria) this;
        }

        public Criteria andMonthNumNotLike(String value) {
            addCriterion("month_num not like", value, "monthNum");
            return (Criteria) this;
        }

        public Criteria andMonthNumIn(List<String> values) {
            addCriterion("month_num in", values, "monthNum");
            return (Criteria) this;
        }

        public Criteria andMonthNumNotIn(List<String> values) {
            addCriterion("month_num not in", values, "monthNum");
            return (Criteria) this;
        }

        public Criteria andMonthNumBetween(String value1, String value2) {
            addCriterion("month_num between", value1, value2, "monthNum");
            return (Criteria) this;
        }

        public Criteria andMonthNumNotBetween(String value1, String value2) {
            addCriterion("month_num not between", value1, value2, "monthNum");
            return (Criteria) this;
        }

        public Criteria andYearRateIsNull() {
            addCriterion("year_rate is null");
            return (Criteria) this;
        }

        public Criteria andYearRateIsNotNull() {
            addCriterion("year_rate is not null");
            return (Criteria) this;
        }

        public Criteria andYearRateEqualTo(String value) {
            addCriterion("year_rate =", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateNotEqualTo(String value) {
            addCriterion("year_rate <>", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateGreaterThan(String value) {
            addCriterion("year_rate >", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateGreaterThanOrEqualTo(String value) {
            addCriterion("year_rate >=", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateLessThan(String value) {
            addCriterion("year_rate <", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateLessThanOrEqualTo(String value) {
            addCriterion("year_rate <=", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateLike(String value) {
            addCriterion("year_rate like", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateNotLike(String value) {
            addCriterion("year_rate not like", value, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateIn(List<String> values) {
            addCriterion("year_rate in", values, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateNotIn(List<String> values) {
            addCriterion("year_rate not in", values, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateBetween(String value1, String value2) {
            addCriterion("year_rate between", value1, value2, "yearRate");
            return (Criteria) this;
        }

        public Criteria andYearRateNotBetween(String value1, String value2) {
            addCriterion("year_rate not between", value1, value2, "yearRate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zq_report_debt_list
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 07 23:32:29 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zq_report_debt_list
     *
     * @mbggenerated Sun Dec 07 23:32:29 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}